### ISSUE TITLE
Open tab in current zone

### ISSUE THREAD

**Issue by Pierll** [madprops/grasshopper#171]
Hello, first of all as a heavy tabs user (1000+) I must say thanks you for this wonderful extension.

Currently the problem im having with it is when I create a new tab (Ctrl+T) it opens it at the end of the tabs list. 
What i wish it could do is opening the tab in the current zone (header) and not skip every zone.

**Comment by madprops** [comment]
Hello. Opening in current zone is a mode I can implement, and an interesting one. However you want it to work on ctrl+t --- That is a browser shortcut, and it uses the new tab rules of the browser. There are several ways to open new tabs from the extension, I can add a zone mode for them. If we wanted it to work on ctrl+t the extension would have to hijack, in a way, new tabs, and change their index by listening to their creation.

Would it be fine for you to use the commands inside the extension for this instead of having to alter native new tab functionality?

**Comment by Pierll** [comment]
Hi, thanks for your quick response. I do not mind using the command ctrl+t (or another shortcut) is just a bonus for me. The main thing is just having the new tab opening in the current zone so i don't have to drag the new tab all the way back to the zone I want.

**Comment by madprops** [comment]
You can already open new tabs below the current tab when you open tabs inside the extension.

Try double clicking empty space in the favorites bar on the left to open a new tab.

There is a setting to control how new tabs get displayed, default is below current.

**Comment by Pierll** [comment]
Oh thanks I didn't know that. Well that's what I needed
