### ISSUE TITLE
Grasshopper v2000

### ISSUE THREAD

**Issue by madprops** [madprops/grasshopper#26]
Big changes.
Profiles are no longer a thing. 
Tabs are edited directly.
Edits are now Color and Title only for now.
Since I had to add an explicit ID Firefox will reset your settings.

Why?

This simplifies edits a lot, and they can be applied to tabs for the remainder of their lifetime.
There's only a simple Color command, instead of having also toggle and tab.
Profiles were hard to work with and confusing.

**Comment by N3C2L** [comment]
Thanks, the update did not reset everything for me, just favorites and profiles, I think.

**Comment by N3C2L** [comment]
If you don't mind: I'd be excited for a new command: "unload other tabs": unloads all tabs except the actual selected tab.

**Comment by madprops** [comment]
Added command `Unload Others` for tabs. Right now it unloads anything, pins etc, after the confirm.
This is on `v2002`.

**Comment by madprops** [comment]
I'm adding `Close Others` on next version.

**Comment by madprops** [comment]
Adding a confirm to include or not pins in `Unload Others`.

**Comment by N3C2L** [comment]
Thanks. What do you think about implementing tab groups with this new tab update? What should be solved first, so that you would consider to implementing them? One of the problems may appear, that searching for tabs may needs to display the group tab name (although perhaps the group name does not match the search criteria). So maybe a checkbox to include group names or exclude them (=flat search). In a search with groups included the group tab names could be displayed above or as a seperate column on the right side of the tabs (to save space).

**Comment by madprops** [comment]
What exactly is a tab group?

**Comment by N3C2L** [comment]
Tab groups lets you organize similar tabs together. With drag and drop.
When one tab is dragged onto another one tab is the parent tab, other tab is the child tab. With a twisty on the parent you can collapse or expand the tab group. the parent tab can have many child tabs. But it's best you try it for yourself in the "sidebery" plugin of firefox. If you've installed it from the firefox addon page, open 2 tabs and drag one tab onto the other tab. Then they are grouped. You can then collapse the 2 tabs when you go to the upper tab (the parent tab), and click on the twisty left of the favicon.

**Comment by madprops** [comment]
I see. I don't plan to add something like that, since I like that lists are purely flat, with other different ways of filtering. I personally have never felt the need to use something like that.

**Comment by madprops** [comment]
I think many features have been added in recent days. I would appreciate if issues from now on focus on bug fixing, stability, performance, etc.

**Comment by N3C2L** [comment]
I understand. Maybe sometime in the future.
Tab groups would have been important to organize a lot of tabs even more. Because you can organize them by topics that are important for your life.
If you ever plan to implement them, I gathered some ideas for tab filtering:

#List last visited group tabs
#Filter all tabs which are not in a group
#Commands: switch to next and previous selected group
#Group focus filtering: command available when a group tab is selected: show only this tab group (with his child tabs ofc.) but hide other tabs.
